from __future__ import annotations

from typing import Any

CXR_TEMPLATES: list[dict[str, Any]] = [
    {
        "template": "What does {finding} mean on a chest X-ray?",
        "difficulty": "easy",
        "domain": "cxr",
        "hop_pattern": [("Finding", "indicates", "Disease")],
        "placeholders": {"finding": "Finding"},
    },
    {
        "template": "Where is {finding} located in the chest?",
        "difficulty": "easy",
        "domain": "cxr",
        "hop_pattern": [("Finding", "located_at", "Anatomy")],
        "placeholders": {"finding": "Finding"},
    },
    {
        "template": "Does {finding1} relate to {finding2}?",
        "difficulty": "easy",
        "domain": "cxr",
        "hop_pattern": [("Finding", "suggestive_of", "Finding")],
        "placeholders": {"finding1": "Finding", "finding2": "Finding"},
    },
    {
        "template": "What disease does {finding} point to?",
        "difficulty": "easy",
        "domain": "cxr",
        "hop_pattern": [("Finding", "indicates", "Disease")],
        "placeholders": {"finding": "Finding"},
    },
    {
        "template": "Which body part does {finding} affect?",
        "difficulty": "easy",
        "domain": "cxr",
        "hop_pattern": [("Finding", "located_at", "Anatomy")],
        "placeholders": {"finding": "Finding"},
    },
    {
        "template": "What anatomical location is associated with {finding} in chest X-rays?",
        "difficulty": "medium",
        "domain": "cxr",
        "hop_pattern": [("Finding", "located_at", "Anatomy")],
        "placeholders": {"finding": "Finding"},
    },
    {
        "template": "Which diseases are indicated by {finding} on CXR?",
        "difficulty": "medium",
        "domain": "cxr",
        "hop_pattern": [("Finding", "indicates", "Disease")],
        "placeholders": {"finding": "Finding"},
    },
    {
        "template": "What CXR findings are suggestive of {finding}?",
        "difficulty": "medium",
        "domain": "cxr",
        "hop_pattern": [("Finding", "suggestive_of", "Finding")],
        "placeholders": {"finding": "Finding"},
    },
    {
        "template": "Show the anatomical site and disease linked to {finding}.",
        "difficulty": "medium",
        "domain": "cxr",
        "hop_pattern": [("Finding", "located_at", "Anatomy"), ("Finding", "indicates", "Disease")],
        "placeholders": {"finding": "Finding"},
    },
    {
        "template": "Which findings modify {finding} and what do they indicate?",
        "difficulty": "medium",
        "domain": "cxr",
        "hop_pattern": [("Finding", "modifies", "Finding"), ("Finding", "indicates", "Disease")],
        "placeholders": {"finding": "Finding"},
    },
    {
        "template": "List the CXR findings that are located at {anatomy} and suggest {finding}.",
        "difficulty": "medium",
        "domain": "cxr",
        "hop_pattern": [("Finding", "located_at", "Anatomy"), ("Finding", "suggestive_of", "Finding")],
        "placeholders": {"anatomy": "Anatomy", "finding": "Finding"},
    },
    {
        "template": "How does {finding} relate to {disease} through anatomical involvement?",
        "difficulty": "medium",
        "domain": "cxr",
        "hop_pattern": [("Finding", "located_at", "Anatomy"), ("Finding", "indicates", "Disease")],
        "placeholders": {"finding": "Finding", "disease": "Disease"},
    },
    {
        "template": "Find all CXR findings that share the anatomical location of {finding} but indicate a different disease.",
        "difficulty": "medium",
        "domain": "cxr",
        "hop_pattern": [("Finding", "located_at", "Anatomy"), ("Finding", "indicates", "Disease")],
        "placeholders": {"finding": "Finding"},
    },
    {
        "template": "What studies for {patient} contain the finding {finding}?",
        "difficulty": "medium",
        "domain": "cxr",
        "hop_pattern": [("Patient", "has_finding", "Finding"), ("Study", "finding_of", "Finding")],
        "placeholders": {"patient": "Patient", "finding": "Finding"},
    },
    {
        "template": "Which modifiers of {finding} are located at {anatomy}?",
        "difficulty": "medium",
        "domain": "cxr",
        "hop_pattern": [("Finding", "modifies", "Finding"), ("Finding", "located_at", "Anatomy")],
        "placeholders": {"finding": "Finding", "anatomy": "Anatomy"},
    },
    {
        "template": "In patients with {disease1}, which CXR findings at {anatomy} also suggest {disease2}?",
        "difficulty": "hard",
        "domain": "cxr",
        "hop_pattern": [("Finding", "located_at", "Anatomy"), ("Finding", "indicates", "Disease"), ("Finding", "suggestive_of", "Finding")],
        "placeholders": {"disease1": "Disease", "anatomy": "Anatomy", "disease2": "Disease"},
    },
    {
        "template": "Identify the chain from {finding} through its modifiers and anatomical site to the parent diseases that subsume {disease}.",
        "difficulty": "hard",
        "domain": "cxr",
        "hop_pattern": [("Finding", "modifies", "Finding"), ("Finding", "located_at", "Anatomy"), ("Finding", "indicates", "Disease"), ("Disease", "subsumes", "Disease")],
        "placeholders": {"finding": "Finding", "disease": "Disease"},
    },
    {
        "template": "Trace the transitive suggestion path from {finding1} through {finding2} to {disease}, constrained to findings at {anatomy}.",
        "difficulty": "hard",
        "domain": "cxr",
        "hop_pattern": [("Finding", "suggestive_of", "Finding"), ("Finding", "suggestive_of", "Finding"), ("Finding", "located_at", "Anatomy"), ("Finding", "indicates", "Disease")],
        "placeholders": {"finding1": "Finding", "finding2": "Finding", "disease": "Disease", "anatomy": "Anatomy"},
    },
    {
        "template": "For {patient}, which CXR findings span both {anatomy1} and {anatomy2}, and what overlapping diseases do they indicate?",
        "difficulty": "hard",
        "domain": "cxr",
        "hop_pattern": [("Patient", "has_finding", "Finding"), ("Finding", "located_at", "Anatomy"), ("Finding", "indicates", "Disease")],
        "placeholders": {"patient": "Patient", "anatomy1": "Anatomy", "anatomy2": "Anatomy"},
    },
]

ECG_TEMPLATES: list[dict[str, Any]] = [
    {
        "template": "What does {finding} mean on an ECG?",
        "difficulty": "easy",
        "domain": "ecg",
        "hop_pattern": [("Finding", "indicates", "Disease")],
        "placeholders": {"finding": "Finding"},
    },
    {
        "template": "Is {finding1} related to {finding2} on ECG?",
        "difficulty": "easy",
        "domain": "ecg",
        "hop_pattern": [("Finding", "suggestive_of", "Finding")],
        "placeholders": {"finding1": "Finding", "finding2": "Finding"},
    },
    {
        "template": "What condition does {finding} suggest?",
        "difficulty": "easy",
        "domain": "ecg",
        "hop_pattern": [("Finding", "indicates", "Disease")],
        "placeholders": {"finding": "Finding"},
    },
    {
        "template": "Does {finding} change how we read {finding2}?",
        "difficulty": "easy",
        "domain": "ecg",
        "hop_pattern": [("Finding", "modifies", "Finding")],
        "placeholders": {"finding": "Finding", "finding2": "Finding"},
    },
    {
        "template": "Which ECG findings are suggestive of {disease}?",
        "difficulty": "medium",
        "domain": "ecg",
        "hop_pattern": [("Finding", "indicates", "Disease")],
        "placeholders": {"disease": "Disease"},
    },
    {
        "template": "What modifiers alter the interpretation of {finding} on ECG?",
        "difficulty": "medium",
        "domain": "ecg",
        "hop_pattern": [("Finding", "modifies", "Finding")],
        "placeholders": {"finding": "Finding"},
    },
    {
        "template": "Which diseases does {finding} indicate, and what other ECG findings suggest the same conditions?",
        "difficulty": "medium",
        "domain": "ecg",
        "hop_pattern": [("Finding", "indicates", "Disease"), ("Finding", "suggestive_of", "Finding")],
        "placeholders": {"finding": "Finding"},
    },
    {
        "template": "Show the ECG findings that suggest {finding} and the diseases they indicate.",
        "difficulty": "medium",
        "domain": "ecg",
        "hop_pattern": [("Finding", "suggestive_of", "Finding"), ("Finding", "indicates", "Disease")],
        "placeholders": {"finding": "Finding"},
    },
    {
        "template": "How many studies for {patient} include the ECG finding {finding}?",
        "difficulty": "medium",
        "domain": "ecg",
        "hop_pattern": [("Patient", "has_finding", "Finding"), ("Study", "finding_of", "Finding")],
        "placeholders": {"patient": "Patient", "finding": "Finding"},
    },
    {
        "template": "List ECG findings that modify {finding} and also indicate {disease}.",
        "difficulty": "medium",
        "domain": "ecg",
        "hop_pattern": [("Finding", "modifies", "Finding"), ("Finding", "indicates", "Disease")],
        "placeholders": {"finding": "Finding", "disease": "Disease"},
    },
    {
        "template": "What other studies does {study} share with through the same patient who has {finding}?",
        "difficulty": "medium",
        "domain": "ecg",
        "hop_pattern": [("Study", "same_patient", "Study"), ("Patient", "has_finding", "Finding")],
        "placeholders": {"study": "Study", "finding": "Finding"},
    },
    {
        "template": "Which ECG findings suggestive of {finding1} also indicate {disease}?",
        "difficulty": "medium",
        "domain": "ecg",
        "hop_pattern": [("Finding", "suggestive_of", "Finding"), ("Finding", "indicates", "Disease")],
        "placeholders": {"finding1": "Finding", "disease": "Disease"},
    },
    {
        "template": "Find ECG findings that are both modified by {finding} and suggestive of {disease}.",
        "difficulty": "medium",
        "domain": "ecg",
        "hop_pattern": [("Finding", "modifies", "Finding"), ("Finding", "suggestive_of", "Finding"), ("Finding", "indicates", "Disease")],
        "placeholders": {"finding": "Finding", "disease": "Disease"},
    },
    {
        "template": "In the ECG context, trace the modifier chain from {finding1} through {finding2} to {disease} and identify any co-occurring findings in the same study.",
        "difficulty": "hard",
        "domain": "ecg",
        "hop_pattern": [("Finding", "modifies", "Finding"), ("Finding", "suggestive_of", "Finding"), ("Finding", "indicates", "Disease"), ("Study", "finding_of", "Finding")],
        "placeholders": {"finding1": "Finding", "finding2": "Finding", "disease": "Disease"},
    },
    {
        "template": "For {patient}, identify transitive ECG suggestion chains from {finding} that converge on {disease}, restricted to studies sharing the same patient.",
        "difficulty": "hard",
        "domain": "ecg",
        "hop_pattern": [("Patient", "has_finding", "Finding"), ("Finding", "suggestive_of", "Finding"), ("Finding", "indicates", "Disease"), ("Study", "same_patient", "Study")],
        "placeholders": {"patient": "Patient", "finding": "Finding", "disease": "Disease"},
    },
    {
        "template": "Identify the complete modifier-suggestion-disease path from {finding} and determine which parent conditions subsume the indicated {disease}.",
        "difficulty": "hard",
        "domain": "ecg",
        "hop_pattern": [("Finding", "modifies", "Finding"), ("Finding", "suggestive_of", "Finding"), ("Finding", "indicates", "Disease"), ("Disease", "subsumes", "Disease")],
        "placeholders": {"finding": "Finding", "disease": "Disease"},
    },
    {
        "template": "Across studies linked by same_patient for {patient}, which ECG findings suggest {finding} and what overlapping diseases do those findings indicate?",
        "difficulty": "hard",
        "domain": "ecg",
        "hop_pattern": [("Study", "same_patient", "Study"), ("Patient", "has_finding", "Finding"), ("Finding", "suggestive_of", "Finding"), ("Finding", "indicates", "Disease")],
        "placeholders": {"patient": "Patient", "finding": "Finding"},
    },
]

CROSS_MODAL_TEMPLATES: list[dict[str, Any]] = [
    {
        "template": "Does {finding_cxr} relate to {finding_ecg}?",
        "difficulty": "easy",
        "domain": "cross_modal",
        "hop_pattern": [("Finding", "suggestive_of", "Finding")],
        "placeholders": {"finding_cxr": "Finding", "finding_ecg": "Finding"},
    },
    {
        "template": "Are {finding1} and {finding2} connected?",
        "difficulty": "easy",
        "domain": "cross_modal",
        "hop_pattern": [("Finding", "suggestive_of", "Finding")],
        "placeholders": {"finding1": "Finding", "finding2": "Finding"},
    },
    {
        "template": "What finding from another modality is linked to {finding}?",
        "difficulty": "easy",
        "domain": "cross_modal",
        "hop_pattern": [("Finding", "suggestive_of", "Finding")],
        "placeholders": {"finding": "Finding"},
    },
    {
        "template": "Which cross-modal finding suggests {finding}?",
        "difficulty": "easy",
        "domain": "cross_modal",
        "hop_pattern": [("Finding", "suggestive_of", "Finding")],
        "placeholders": {"finding": "Finding"},
    },
    {
        "template": "Which cross-modal findings bridged by {disease} connect {finding1} to {finding2}?",
        "difficulty": "medium",
        "domain": "cross_modal",
        "hop_pattern": [("Finding", "indicates", "Disease"), ("Finding", "indicates", "Disease"), ("Finding", "suggestive_of", "Finding")],
        "placeholders": {"disease": "Disease", "finding1": "Finding", "finding2": "Finding"},
    },
    {
        "template": "What CXR findings suggest the same diseases as {finding_ecg}?",
        "difficulty": "medium",
        "domain": "cross_modal",
        "hop_pattern": [("Finding", "indicates", "Disease"), ("Finding", "suggestive_of", "Finding")],
        "placeholders": {"finding_ecg": "Finding"},
    },
    {
        "template": "List the cross-modal suggestive links from {finding} to findings in other modalities.",
        "difficulty": "medium",
        "domain": "cross_modal",
        "hop_pattern": [("Finding", "suggestive_of", "Finding")],
        "placeholders": {"finding": "Finding"},
    },
    {
        "template": "Which diseases are indicated by both {finding_cxr} and its cross-modal suggestive findings?",
        "difficulty": "medium",
        "domain": "cross_modal",
        "hop_pattern": [("Finding", "suggestive_of", "Finding"), ("Finding", "indicates", "Disease")],
        "placeholders": {"finding_cxr": "Finding"},
    },
    {
        "template": "How does {finding1} connect to {finding2} through shared disease indications?",
        "difficulty": "medium",
        "domain": "cross_modal",
        "hop_pattern": [("Finding", "indicates", "Disease"), ("Finding", "indicates", "Disease")],
        "placeholders": {"finding1": "Finding", "finding2": "Finding"},
    },
    {
        "template": "Find the suggestive chain from {finding1} through {finding2} and the diseases they jointly indicate.",
        "difficulty": "medium",
        "domain": "cross_modal",
        "hop_pattern": [("Finding", "suggestive_of", "Finding"), ("Finding", "indicates", "Disease")],
        "placeholders": {"finding1": "Finding", "finding2": "Finding"},
    },
    {
        "template": "What cross-modal findings share the anatomical location {anatomy} with {finding}?",
        "difficulty": "medium",
        "domain": "cross_modal",
        "hop_pattern": [("Finding", "located_at", "Anatomy"), ("Finding", "suggestive_of", "Finding")],
        "placeholders": {"anatomy": "Anatomy", "finding": "Finding"},
    },
    {
        "template": "For {patient}, which cross-modal suggestive pairs appear across their studies?",
        "difficulty": "medium",
        "domain": "cross_modal",
        "hop_pattern": [("Patient", "has_finding", "Finding"), ("Study", "same_patient", "Study"), ("Finding", "suggestive_of", "Finding")],
        "placeholders": {"patient": "Patient"},
    },
    {
        "template": "Identify the ECG findings that are cross-modally suggestive of {finding_cxr} and indicate {disease}.",
        "difficulty": "medium",
        "domain": "cross_modal",
        "hop_pattern": [("Finding", "suggestive_of", "Finding"), ("Finding", "indicates", "Disease")],
        "placeholders": {"finding_cxr": "Finding", "disease": "Disease"},
    },
    {
        "template": "In patients with {disease1}, which cross-modal findings bridged through {disease2} suggest comorbid {disease3}?",
        "difficulty": "hard",
        "domain": "cross_modal",
        "hop_pattern": [("Finding", "indicates", "Disease"), ("Finding", "indicates", "Disease"), ("Finding", "suggestive_of", "Finding"), ("Finding", "indicates", "Disease")],
        "placeholders": {"disease1": "Disease", "disease2": "Disease", "disease3": "Disease"},
    },
    {
        "template": "Trace the full cross-modal suggestion path from {finding_cxr} through {finding_ecg} to {disease}, and identify the parent conditions that subsume it.",
        "difficulty": "hard",
        "domain": "cross_modal",
        "hop_pattern": [("Finding", "suggestive_of", "Finding"), ("Finding", "indicates", "Disease"), ("Disease", "subsumes", "Disease")],
        "placeholders": {"finding_cxr": "Finding", "finding_ecg": "Finding", "disease": "Disease"},
    },
    {
        "template": "Across same-patient studies for {patient}, find the transitive cross-modal suggestion chain from {finding1} to {finding2} and the anatomical locations they share.",
        "difficulty": "hard",
        "domain": "cross_modal",
        "hop_pattern": [("Study", "same_patient", "Study"), ("Finding", "suggestive_of", "Finding"), ("Finding", "suggestive_of", "Finding"), ("Finding", "located_at", "Anatomy")],
        "placeholders": {"patient": "Patient", "finding1": "Finding", "finding2": "Finding"},
    },
    {
        "template": "Identify multi-hop cross-modal paths where {finding} at {anatomy} suggests findings indicating {disease}, constrained to studies of {patient}.",
        "difficulty": "hard",
        "domain": "cross_modal",
        "hop_pattern": [("Finding", "located_at", "Anatomy"), ("Finding", "suggestive_of", "Finding"), ("Finding", "indicates", "Disease"), ("Study", "same_patient", "Study"), ("Patient", "has_finding", "Finding")],
        "placeholders": {"finding": "Finding", "anatomy": "Anatomy", "disease": "Disease", "patient": "Patient"},
    },
]

DISEASE_TEMPLATES: list[dict[str, Any]] = [
    {
        "template": "What findings point to {disease}?",
        "difficulty": "easy",
        "domain": "disease",
        "hop_pattern": [("Finding", "indicates", "Disease")],
        "placeholders": {"disease": "Disease"},
    },
    {
        "template": "Does {disease1} include {disease2}?",
        "difficulty": "easy",
        "domain": "disease",
        "hop_pattern": [("Disease", "subsumes", "Disease")],
        "placeholders": {"disease1": "Disease", "disease2": "Disease"},
    },
    {
        "template": "What is {disease} a type of?",
        "difficulty": "easy",
        "domain": "disease",
        "hop_pattern": [("Disease", "subsumes", "Disease")],
        "placeholders": {"disease": "Disease"},
    },
    {
        "template": "Which findings indicate {disease}?",
        "difficulty": "easy",
        "domain": "disease",
        "hop_pattern": [("Finding", "indicates", "Disease")],
        "placeholders": {"disease": "Disease"},
    },
    {
        "template": "Which specific findings across modalities are indicators of {disease}?",
        "difficulty": "medium",
        "domain": "disease",
        "hop_pattern": [("Finding", "indicates", "Disease")],
        "placeholders": {"disease": "Disease"},
    },
    {
        "template": "What parent conditions subsume {disease}?",
        "difficulty": "medium",
        "domain": "disease",
        "hop_pattern": [("Disease", "subsumes", "Disease")],
        "placeholders": {"disease": "Disease"},
    },
    {
        "template": "Which findings that indicate {disease} are located at {anatomy}?",
        "difficulty": "medium",
        "domain": "disease",
        "hop_pattern": [("Finding", "indicates", "Disease"), ("Finding", "located_at", "Anatomy")],
        "placeholders": {"disease": "Disease", "anatomy": "Anatomy"},
    },
    {
        "template": "List the subsumed conditions under {disease} and their associated findings.",
        "difficulty": "medium",
        "domain": "disease",
        "hop_pattern": [("Disease", "subsumes", "Disease"), ("Finding", "indicates", "Disease")],
        "placeholders": {"disease": "Disease"},
    },
    {
        "template": "How are {disease1} and {disease2} related through the subsumption hierarchy?",
        "difficulty": "medium",
        "domain": "disease",
        "hop_pattern": [("Disease", "subsumes", "Disease"), ("Disease", "subsumes", "Disease")],
        "placeholders": {"disease1": "Disease", "disease2": "Disease"},
    },
    {
        "template": "Which findings indicate both {disease1} and {disease2}?",
        "difficulty": "medium",
        "domain": "disease",
        "hop_pattern": [("Finding", "indicates", "Disease"), ("Finding", "indicates", "Disease")],
        "placeholders": {"disease1": "Disease", "disease2": "Disease"},
    },
    {
        "template": "For {disease}, find the suggestive findings that also indicate its parent condition.",
        "difficulty": "medium",
        "domain": "disease",
        "hop_pattern": [("Finding", "indicates", "Disease"), ("Disease", "subsumes", "Disease"), ("Finding", "suggestive_of", "Finding")],
        "placeholders": {"disease": "Disease"},
    },
    {
        "template": "What modifiers change the clinical significance of findings that indicate {disease}?",
        "difficulty": "medium",
        "domain": "disease",
        "hop_pattern": [("Finding", "indicates", "Disease"), ("Finding", "modifies", "Finding")],
        "placeholders": {"disease": "Disease"},
    },
    {
        "template": "Show the disease hierarchy from {disease} up to its most general parent and all findings at each level.",
        "difficulty": "medium",
        "domain": "disease",
        "hop_pattern": [("Disease", "subsumes", "Disease"), ("Finding", "indicates", "Disease")],
        "placeholders": {"disease": "Disease"},
    },
    {
        "template": "Identify the transitive disease hierarchy connecting {finding} through {disease} to its parent conditions and their cross-modal indicators.",
        "difficulty": "hard",
        "domain": "disease",
        "hop_pattern": [("Finding", "indicates", "Disease"), ("Disease", "subsumes", "Disease"), ("Finding", "suggestive_of", "Finding")],
        "placeholders": {"finding": "Finding", "disease": "Disease"},
    },
    {
        "template": "For {patient} with {disease}, trace the subsumption chain and identify findings at {anatomy} that differentiate {disease1} from its parent {disease2}.",
        "difficulty": "hard",
        "domain": "disease",
        "hop_pattern": [("Patient", "has_finding", "Finding"), ("Disease", "subsumes", "Disease"), ("Finding", "indicates", "Disease"), ("Finding", "located_at", "Anatomy")],
        "placeholders": {"patient": "Patient", "disease": "Disease", "anatomy": "Anatomy", "disease1": "Disease", "disease2": "Disease"},
    },
    {
        "template": "Map the full inference chain from {finding} at {anatomy} through the disease hierarchy to {disease}, including all cross-modal suggestive findings at each level.",
        "difficulty": "hard",
        "domain": "disease",
        "hop_pattern": [("Finding", "located_at", "Anatomy"), ("Finding", "indicates", "Disease"), ("Disease", "subsumes", "Disease"), ("Finding", "suggestive_of", "Finding")],
        "placeholders": {"finding": "Finding", "anatomy": "Anatomy", "disease": "Disease"},
    },
    {
        "template": "In the disease taxonomy rooted at {disease1}, which leaf conditions are indicated by findings that also suggest {finding}, and what anatomical locations do those findings share?",
        "difficulty": "hard",
        "domain": "disease",
        "hop_pattern": [("Disease", "subsumes", "Disease"), ("Finding", "indicates", "Disease"), ("Finding", "suggestive_of", "Finding"), ("Finding", "located_at", "Anatomy")],
        "placeholders": {"disease1": "Disease", "finding": "Finding"},
    },
]

ANATOMY_TEMPLATES: list[dict[str, Any]] = [
    {
        "template": "What findings are at {anatomy}?",
        "difficulty": "easy",
        "domain": "anatomy",
        "hop_pattern": [("Finding", "located_at", "Anatomy")],
        "placeholders": {"anatomy": "Anatomy"},
    },
    {
        "template": "Which body part does {finding} involve?",
        "difficulty": "easy",
        "domain": "anatomy",
        "hop_pattern": [("Finding", "located_at", "Anatomy")],
        "placeholders": {"finding": "Finding"},
    },
    {
        "template": "Where in the body is {finding} found?",
        "difficulty": "easy",
        "domain": "anatomy",
        "hop_pattern": [("Finding", "located_at", "Anatomy")],
        "placeholders": {"finding": "Finding"},
    },
    {
        "template": "What anatomy is linked to {finding}?",
        "difficulty": "easy",
        "domain": "anatomy",
        "hop_pattern": [("Finding", "located_at", "Anatomy")],
        "placeholders": {"finding": "Finding"},
    },
    {
        "template": "Which findings are located at {anatomy} and indicate {disease}?",
        "difficulty": "medium",
        "domain": "anatomy",
        "hop_pattern": [("Finding", "located_at", "Anatomy"), ("Finding", "indicates", "Disease")],
        "placeholders": {"anatomy": "Anatomy", "disease": "Disease"},
    },
    {
        "template": "What diseases are associated with findings at {anatomy}?",
        "difficulty": "medium",
        "domain": "anatomy",
        "hop_pattern": [("Finding", "located_at", "Anatomy"), ("Finding", "indicates", "Disease")],
        "placeholders": {"anatomy": "Anatomy"},
    },
    {
        "template": "How many findings at {anatomy} suggest {finding}?",
        "difficulty": "medium",
        "domain": "anatomy",
        "hop_pattern": [("Finding", "located_at", "Anatomy"), ("Finding", "suggestive_of", "Finding")],
        "placeholders": {"anatomy": "Anatomy", "finding": "Finding"},
    },
    {
        "template": "Which anatomical locations have findings that modify {finding}?",
        "difficulty": "medium",
        "domain": "anatomy",
        "hop_pattern": [("Finding", "located_at", "Anatomy"), ("Finding", "modifies", "Finding")],
        "placeholders": {"finding": "Finding"},
    },
    {
        "template": "List the diseases indicated by findings at both {anatomy1} and {anatomy2}.",
        "difficulty": "medium",
        "domain": "anatomy",
        "hop_pattern": [("Finding", "located_at", "Anatomy"), ("Finding", "indicates", "Disease")],
        "placeholders": {"anatomy1": "Anatomy", "anatomy2": "Anatomy"},
    },
    {
        "template": "What cross-modal suggestive findings share the anatomical site {anatomy}?",
        "difficulty": "medium",
        "domain": "anatomy",
        "hop_pattern": [("Finding", "located_at", "Anatomy"), ("Finding", "suggestive_of", "Finding")],
        "placeholders": {"anatomy": "Anatomy"},
    },
    {
        "template": "Find findings at {anatomy} that are modifiers of other findings indicating {disease}.",
        "difficulty": "medium",
        "domain": "anatomy",
        "hop_pattern": [("Finding", "located_at", "Anatomy"), ("Finding", "modifies", "Finding"), ("Finding", "indicates", "Disease")],
        "placeholders": {"anatomy": "Anatomy", "disease": "Disease"},
    },
    {
        "template": "For {patient}, which anatomical sites have findings shared across multiple studies?",
        "difficulty": "medium",
        "domain": "anatomy",
        "hop_pattern": [("Patient", "has_finding", "Finding"), ("Finding", "located_at", "Anatomy"), ("Study", "same_patient", "Study")],
        "placeholders": {"patient": "Patient"},
    },
    {
        "template": "Which findings located at {anatomy} have cross-modal suggestions that indicate {disease}?",
        "difficulty": "medium",
        "domain": "anatomy",
        "hop_pattern": [("Finding", "located_at", "Anatomy"), ("Finding", "suggestive_of", "Finding"), ("Finding", "indicates", "Disease")],
        "placeholders": {"anatomy": "Anatomy", "disease": "Disease"},
    },
    {
        "template": "Across same-patient studies, which anatomical locations host findings with cross-modal links to {disease}?",
        "difficulty": "hard",
        "domain": "anatomy",
        "hop_pattern": [("Study", "same_patient", "Study"), ("Finding", "located_at", "Anatomy"), ("Finding", "suggestive_of", "Finding"), ("Finding", "indicates", "Disease")],
        "placeholders": {"disease": "Disease"},
    },
    {
        "template": "Map the multi-hop path from {anatomy} through findings and their suggestive links to the disease hierarchy rooted at {disease}.",
        "difficulty": "hard",
        "domain": "anatomy",
        "hop_pattern": [("Finding", "located_at", "Anatomy"), ("Finding", "suggestive_of", "Finding"), ("Finding", "indicates", "Disease"), ("Disease", "subsumes", "Disease")],
        "placeholders": {"anatomy": "Anatomy", "disease": "Disease"},
    },
    {
        "template": "For {patient}, identify anatomical regions where findings at {anatomy1} have modifiers that cross-modally suggest findings at {anatomy2} indicating {disease}.",
        "difficulty": "hard",
        "domain": "anatomy",
        "hop_pattern": [("Patient", "has_finding", "Finding"), ("Finding", "located_at", "Anatomy"), ("Finding", "modifies", "Finding"), ("Finding", "suggestive_of", "Finding"), ("Finding", "indicates", "Disease")],
        "placeholders": {"patient": "Patient", "anatomy1": "Anatomy", "anatomy2": "Anatomy", "disease": "Disease"},
    },
    {
        "template": "Identify findings at {anatomy} whose modifiers and suggestive chains converge on {disease}, and trace the subsumption hierarchy to its root.",
        "difficulty": "hard",
        "domain": "anatomy",
        "hop_pattern": [("Finding", "located_at", "Anatomy"), ("Finding", "modifies", "Finding"), ("Finding", "suggestive_of", "Finding"), ("Finding", "indicates", "Disease"), ("Disease", "subsumes", "Disease")],
        "placeholders": {"anatomy": "Anatomy", "disease": "Disease"},
    },
]

PROMPT_TEMPLATES: dict[str, list[dict[str, Any]]] = {
    "cxr": CXR_TEMPLATES,
    "ecg": ECG_TEMPLATES,
    "cross_modal": CROSS_MODAL_TEMPLATES,
    "disease": DISEASE_TEMPLATES,
    "anatomy": ANATOMY_TEMPLATES,
}

ALL_TEMPLATES: list[dict[str, Any]] = (
    CXR_TEMPLATES + ECG_TEMPLATES + CROSS_MODAL_TEMPLATES + DISEASE_TEMPLATES + ANATOMY_TEMPLATES
)